/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file will not be overwritten by default.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace SSoTme.Default.Lib
{                            
    public partial class Photo 
    {
        public Photo()
        {
            this.InitPoco();
        }
    }
}